#druid连接配置
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/game_community?serverTimezone=UTC
      username: root
      password: 1024

  #邮件相关配置
  mail:
    host: smtp.163.com
    port: 465
    default-encoding: UTF-8
    username: cqk428010518@163.com
    password: QTQYVIJMXZAUNJZS
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            socketFactory:
              port: 465
              class: javax.net.ssl.SSLSocketFactory

#jetCache
jetcache: #redis数据库，安装默认无密码，如有密码，自行修改
  remote:
    default:
      type: redis
      host: localhost
      port: 6379
      poolConfig:
        maxTotal: 50

#日志文件
logging:
  level:
    root: info
  file:
    name: log/log.txt

#配置属性
static:
  #wins静态文件位置
  base-dir: "E:/02-javaStu/97-Demo/Game_Community/"
  #linux静态文件位置
  #base-dir: "/www/wwwroot/game_community/static/"