# XXXX内容为账号密码，自行修改

#druid连接配置
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/game_community?serverTimezone=UTC
      username: XXXX #mysql数据库用户名
      password: XXXX #密码

  #邮件相关配置
  mail: #发送验证码使用163邮箱，如用其他，自行修改
    host: smtp.163.com
    port: 465
    default-encoding: UTF-8
    username: XXXX #163邮箱号
    password: XXXX #smtp授权密码
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            socketFactory:
              port: 465
              class: javax.net.ssl.SSLSocketFactory

#jetCache
jetcache: #redis数据库，安装默认无密码，如有密码，自行修改
  remote:
    default:
      type: redis
      host: localhost
      port: 6379
      poolConfig:
        maxTotal: 50

#配置属性
#项目的静态图片以及帖子上传图片存储的本地位置，自行修改，项目中img文件夹所在位置，img文件夹可自行处理需存放路径
static:
  #wins静态文件位置
  base-dir: "E:/02-javaStu/97-Demo/Game_Community/"